name: Execução doos testes unitarios com jest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     - name: checkout do repositorio
       uses:: action/checkout@v4

     - name: configurar Node.JS
       uses: action/stup-node@v3
       with:
         node-version: 18
     
     - name: Instalar dependências
       run: npm install
     
     - name: Executar testes
       run: npm run test
